### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by dpsanders** [Luthaf/Conda.jl#19] opened 2015-10-14 14:19 UTC
It would be great to have support for Python 3. (I can't find it in the package.)

**Comment by Luthaf** [comment] 2015-10-14 16:51
It looks like conda do not provide a separated python3 package. There is a `python==3.5.0` package, but installing it override the global python version.

```
$ conda search -f python
Fetching package metadata: ....
python                       1.0.1                         0  defaults
                             2.6.8                         1  defaults
                             2.6.8                         2  defaults
                             2.6.8                         3  defaults
                             2.6.8                         4  defaults
                             2.6.8                         5  defaults
                             2.6.8                         6  defaults
                             2.6.8                         7  defaults
                             2.6.8                         8  defaults
                             2.6.8                         9  defaults
                             2.6.8                        10  defaults
                             2.6.9                         0  defaults
                             2.6.9                         1  defaults
                             2.7.3                         2  defaults
                             2.7.3                         3  defaults
                             2.7.3                         4  defaults
                             2.7.3                         5  defaults
                             2.7.3                         6  defaults
                             2.7.3                         7  defaults
                             2.7.4                         0  defaults
                             2.7.4                         1  defaults
                             2.7.5                         0  defaults
                             2.7.5                         1  defaults
                             2.7.5                         2  defaults
                             2.7.5                         3  defaults
                             2.7.6                         0  defaults
                             2.7.6                         1  defaults
                             2.7.6                         2  defaults
                             2.7.7                         0  defaults
                             2.7.7                         2  defaults
                             2.7.8                         0  defaults
                             2.7.8                         1  defaults
                             2.7.9                         0  defaults
                             2.7.9                        d1  defaults        [debug]
                          .  2.7.9                         1  defaults
                             2.7.10                       d0  defaults        [debug]
                          .  2.7.10                        0  defaults
                          *  2.7.10                        1  defaults
                             3.3.0                         3  defaults
                             3.3.0                         4  defaults
                             3.3.1                         0  defaults
                             3.3.2                         0  defaults
                             3.3.2                         1  defaults
                             3.3.3                         0  defaults
                             3.3.3                         1  defaults
                             3.3.4                         0  defaults
                             3.3.5                         0  defaults
                             3.3.5                         1  defaults
                             3.3.5                         2  defaults
                             3.3.5                         3  defaults
                             3.4.0                         0  defaults
                             3.4.1                         0  defaults
                             3.4.1                         1  defaults
                             3.4.1                         2  defaults
                             3.4.1                         3  defaults
                             3.4.1                         4  defaults
                             3.4.2                         0  defaults
                             3.4.3                         0  defaults
                             3.5.0rc4                      0  defaults
                             3.5.0                         0  defaults
$ conda install python==3.5.0
Fetching package metadata: ....
Solving package specifications: ............
Package plan for installation in environment /opt/miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    xz-5.0.5                   |                0         132 KB
    python-3.5.0               |                0        12.7 MB
    conda-env-2.4.2            |           py35_0          24 KB
    pycosat-0.6.1              |           py35_0          53 KB
    pyyaml-3.11                |           py35_1         129 KB
    requests-2.8.1             |           py35_0         646 KB
    setuptools-18.4            |           py35_0         345 KB
    wheel-0.26.0               |           py35_1          77 KB
    conda-3.18.2               |           py35_0         176 KB
    pip-7.1.2                  |           py35_0         1.4 MB
    ------------------------------------------------------------
                                           Total:        15.7 MB

The following NEW packages will be INSTALLED:

    xz:         5.0.5-0

The following packages will be UPDATED:

    conda:      3.18.1-py27_0 --> 3.18.2-py35_0
    conda-env:  2.4.2-py27_0  --> 2.4.2-py35_0
    pip:        7.1.2-py27_0  --> 7.1.2-py35_0
    pycosat:    0.6.1-py27_0  --> 0.6.1-py35_0
    python:     2.7.10-1      --> 3.5.0-0
    pyyaml:     3.11-py27_1   --> 3.11-py35_1
    requests:   2.7.0-py27_0  --> 2.8.1-py35_0
    setuptools: 18.3.2-py27_0 --> 18.4-py35_0
    wheel:      0.26.0-py27_1 --> 0.26.0-py35_1

Proceed ([y]/n)? n
```

Using `miniconda3` instead of `miniconda` will do the same thing (install Python 3, and not Python 2). 

The best way I can think to in order to provide both Python 2 and Python 3 would be to use the conda environments. But then you get a state machine, and have to remember switching state again and again.

What would be your use case of having both versions installed ?

**Comment by dpsanders** [comment] 2015-10-14 18:56
My use case is a dependency which requires Python 3. I do not wish to force the user to upgrade any pre-existing Python installation from Python 2 to Python 3 (e.g. from IJulia etc.)

It sounds like I could just create a local conda environment and ensure Python 3 is installed there. Is there some way to do so using the `Conda.jl` package? Or just by shelling out somehow?

**Comment by Luthaf** [comment] 2015-10-14 19:44
Conda environments are not exposed from `Conda.jl`. So you could shell out using `run('Conda.conda ...')`, and manage the corresponding environment (activating and deactivating it); or we can try to design a way to have them easily accessible from `Conda.jl`.

**Comment by dpsanders** [comment] 2015-10-15 03:21
Thanks. I've tried shelling out, and can successfully create an environment but can't seem to do `source activate NAME`, presumably since that is a bash command.

Note that to use `Conda.conda` inside `run`, it's necessary to do

```
run(`$(Conda.conda)...`)
```
e.g.
```
run(`$(Conda.conda) create --name temp python=3`)
```
Maybe there could be a `Conda.conda_cmd` (or whatever) function that would send its arguments straight to `conda`.

**Comment by dpsanders** [comment] 2015-10-15 03:24
Apparently `activate` is just to manipulate the path. So a simple interface should be able to be provided by `Conda.jl`.

**Comment by Luthaf** [comment] 2015-10-15 08:22
> Maybe there could be a Conda.conda_cmd (or whatever) function that would send its arguments straight to conda.

Why not, but this would be intended for internal use at first.

> Apparently activate is just to manipulate the path. So a simple interface should be able to be provided by Conda.jl.

The functionality is easy to add. My concern can be describe in the case you have two packages `Foo.jl` and `Bar.jl` which both uses `Conda.jl` for providing the `libfoo` and `libbar` dependencies, but `Foo.jl` uses the Python 3 environment, and `Bar.jl` do not. Now, what happen if the user run 

```
julia> using Foo

julia> using Bar

```

**Comment by dpsanders** [comment] 2015-10-18 06:17
Good question, I'm not sure. But this is also a problem for two Python packages that need different Python versions. (And maybe the answer is that Python 3 should be the default these days.)

**Comment by jakirkham** [comment] 2015-11-25 13:41
@Luthaf, how are you using `conda` currently? I would think that using one environment that is not `root` (e.g. `juliaenv` or `julia`) should be sufficient for solving this problem. This way if you try to install `python` 3.4 or 3.5, it will automatically update your dependencies or issue an appropriate error about not having a `python` 3.x version.

**Comment by Luthaf** [comment] 2015-11-25 14:12
`conda` is currently used in a root environment, but this can change if we win the ability of getting errors from conda if we try to install a version of Python which is not supported by some other package already installed. I'll have a look into this.

**Comment by stevengj** [comment] 2015-11-25 18:46
Honestly, I think that Conda should pick one Python version and stick with it.  If users want anything else, they can install their own Python distro, e.g. the full Anaconda.  The whole point of Conda is to have fully automated installation with sensible defaults.

Maybe at some point the default should be Python 3, but I think Python 2 is probably the more reliable option at this point for scientific packages (it is still far more tested because it is the default for Anaconda).  My inclination would be wait for Anaconda itself to switch its default.

@dpsanders, can you explain more about your use case?  PyCall can only be built for one version of Python at a time, so you can't switch it to using Python3 just for one package.

**Comment by jakirkham** [comment] 2015-11-25 19:11
@Luthaf, you have to `source` something, but it's actually [`python`]( https://github.com/conda/conda/blob/master/conda/cli/activate.py ). I am guessing the issue is that you are shelling out every time and the environment would be lost? Honestly, the activate script doesn't do anything to magical. It just makes sure the right environment is on your path and the old environment is removed. So, this could be handled internally. Additionally, you may want to handle libs and includes at build time.

**Comment by jakirkham** [comment] 2015-11-25 19:26
@stevengj, I'm trying to follow you, but I think I may be loosing you a bit.

> Honestly, I think that Conda should pick one Python version and stick with it. If users want anything else, they can install their own Python distro, e.g. the full Anaconda. The whole point of Conda is to have fully automated installation with sensible defaults.

I'm assuming you mean Conda.jl here. Is it feasible for Julia users to have an external distribution of conda that they use with Python? I thought everything was packaged internally so doing something might be a bit complicated and fragile, no?

> Maybe at some point the default should be Python 3, but I think Python 2 is probably the more reliable option at this point for scientific packages

Most of the basic packages (e.g. `numpy`, `scipy`, most of `jupyter`) work on both. However, Python 2 is probably the most frequently used for these problems so I agree it remains a good default choice. There are some packages only written for Python 2 that never got ported. However, there are some libraries that are Python 3 only, which may or may not be backported (e.g. some parts of `jupyter`).

> My inclination would be wait for Anaconda itself to switch its default.

There are distributions of Anaconda and Miniconda with Python 2 or 3 as the root environment. Waiting out some switch here is ill-advised due to the number of users still on Python 2.

> PyCall can only be built for one version of Python at a time, so you can't switch it to using Python3 just for one package.

How does this build happen? Is this through `conda build` or some internal Julia mechanism? If the former, you could design recipes that restrict the python version for each build of `PyCall`. This way when the `python` version changes, you can swap one out for the other.

If there are two environments with two different `python`s (2.7 and 3.4 or 3.5), this problem could be solved by not having to swap `PyCall`, but simply installing it in each environment as needed.

**Comment by stevengj** [comment] 2015-11-25 21:42
@jakirkham, using Julia with Conda.jl is only a very recent thing.  Until recently, you *only* used Julia with an external Python distro, and that is probably still the most common scenario.

PyCall is configured in `Pkg.build("PyCall")`.  This is when it figures out where `libpython` is, what the paths are, whether to use the Python 2 or Python 3 APIs, etcetera.   You can switch PyCall to a different version of Python by re-running `Pkg.build("PyCall")` after setting `ENV["PYTHON"]="/path/to/different/python"`.  But doing that changes what Python will be loaded in *all* Julia scripts that employ PyCall.

**Comment by Luthaf** [comment] 2016-06-30 08:46
This problem should be resolved with PyCall.jl, to see if there is a way to have both of Python 2 and 3. Else @stevengj message bellow explain how to switch from one to the other.

Conda.jl itself does not care about which version of Python it is running.

**Closed by Luthaf** 2016-06-30 08:46 UTC
